site_name:           Develop GPU Software With Julia
repo_url:            https://github.com/jenni-westoby/Julia_GPU_examples.git
site_description:    In this tutorial, I will guide you through the full workflow of writing a basic program in Julia that will run on GPU.
site_author:         Jenni Westoby


markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'src'

pages:
- Introduction: index.md
- Getting Started:
  - Set up your GPU: Accessing_GPUs.md
